[pytest]
testpaths = tests
addopts = -q -s
filterwarnings =
    ignore:The 'timeout' parameter is deprecated\..*:DeprecationWarning
    ignore:The 'verify' parameter is deprecated\..*:DeprecationWarning
