"""make user year nullable

Revision ID: 1765838f1982
Revises: 99deb80e0474
Create Date: 2026-02-25 16:47:59.585428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1765838f1982'
down_revision: Union[str, Sequence[str], None] = '99deb80e0474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'year',
               existing_type=postgresql.ENUM('first', 'second', 'third', 'fourth', 'other', name='appyear'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'year',
               existing_type=postgresql.ENUM('first', 'second', 'third', 'fourth', 'other', name='appyear'),
               nullable=False)
    # ### end Alembic commands ###
