"""added team application template

Revision ID: 1b4698e52fa0
Revises: 1765838f1982
Create Date: 2026-03-17 13:40:09.681759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b4698e52fa0'
down_revision: Union[str, Sequence[str], None] = '1765838f1982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('application_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # Add with DEFAULT so existing rows get populated, then drop the default.
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.alter_column('users', 'is_active', server_default=None)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('teams', 'application_template')
    # ### end Alembic commands ###
