"""uers year

Revision ID: 99deb80e0474
Revises: 3a5da0dda4ee
Create Date: 2026-02-25 15:55:12.769354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99deb80e0474'
down_revision: Union[str, Sequence[str], None] = '3a5da0dda4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('year', sa.Enum('first', 'second', 'third', 'fourth', 'other', name='appyear'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'year')
    # ### end Alembic commands ###
